### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by JsonDeveloper** [EvgeniyMedyankin/homeworks#1]
### Нерациональное использование SVG графики: 
1. Изображение не сжато. 
Тем самым исходный вес граф. элемента: 4101 Б. 
При применении SVGO инструмента: SVG можно сократить вес граф. элемента до: 3259 Б.

2. В SVG графике присутствует растровая графика - что сводит на нет целесообразность SVG (как минимум из-за base64 увеличивается вес картинки ± на 20%). В таком случае целесообразней использовать webp/webm. 

### UX:
Целесообразно поставить focus на первый элемент формы (аттрибут autofocus) для удобства пользователя. [homeworks/javascript/credit_bank/index.html 32 line](https://github.com/EvgeniyMedyankin/homeworks/blob/a651d354661e5331b916403fe9e36ed4a76266a6/javascript/credit_bank/index.html#L32)

### Использование устаревших CSS свойств 
[homeworks/javascript/credit_bank/css/style.css](https://github.com/EvgeniyMedyankin/homeworks/blob/a651d354661e5331b916403fe9e36ed4a76266a6/javascript/credit_bank/css/style.css#L255)
Если опираться на инструмент [caniuse](https://caniuse.com/#search=%40keyframes). При использовании CSS анимации - нету смысла использовать `-webkit-` префикса. Chrome с 2015 года полностью соотвествует w3 стандартам касательно анимации. 
 
Если есть цель полной поддержке древних браузеров (±0.4% браузеров) - то стоит воспользоваться CSS препроцессором для приведения CSS кода при компиляции к поддержки требуемых динозавров.

**Comment by EvgeniyMedyankin** [comment]
Спасибо! Это состряпаный на скорую руку проект тупо для выполнения домашек. Он не то что не соответствует стандартам, он попросту весь выполнен  через ж... (с использованием минимального функционала и начальных знаний) как этого требует программа.
